name: Chay Bot Hang Ngay
on:
  schedule:
    - cron: '0 1 * * *' # Chạy lúc 8h sáng VN
  workflow_dispatch: # Cho phép bấm nút chạy tay

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      G_SHEET_CREDS: ${{ secrets.G_SHEET_CREDS }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: python daily_bot.py
